type = "offchainreporting"
schemaVersion = 1
evmChainID = 4200
name = "OCR: ETH/USD"
contractAddress = "0xbcFf21711F6e71887982C96A5aaC53A324351dfA"
externalJobID = "1f6ccbfd-5b9d-4793-8393-f099f7673b03"
p2pv2Bootstrappers = [
    "12D3KooWMjmCxyEaSSWoatbKfURxcVjMsdJbyaqNwpKndf3yAium@172.20.21.241:6660",
    "12D3KooWJEcoXwVrRSPW9oiXco9scoZ6bpYHSBuNLP1tULj8hdyX@172.20.52.188:6660",
]
isBootstrapPeer = false
keyBundleID = "8b854538e7b864dae48932fd66a87b501918eb5a8308dcd7038e30acd9bd6568"
monitoringEndpoint = "apro.org:4321"
transmitterAddress = "0x3d28d50D479810A28F61fae2b6a9F0109167A14f"
observationTimeout = "10s"
blockchainTimeout = "20s"
contractConfigTrackerSubscribeInterval = "2m"
contractConfigTrackerPollInterval = "1m"
contractConfigConfirmations = 3
observationSource = """
encode_decimals [type="ethabiencode" abi="decimals()" data=""]
decimals_call   [type="ethcall" contract="0xbcFf21711F6e71887982C96A5aaC53A324351dfA" data="$(encode_decimals)"  evmChainID="4200"]
decode_decimals [type="ethabidecode" abi="uint32 decimals"  data="$(decimals_call)"]
decimals_pow    [type="pow" input="10"  times="$(decode_decimals.decimals)"]
encode_decimals -> decimals_call -> decode_decimals -> decimals_pow

get_price_cryptocompare_usdt    [type="http" method=GET retries=2 url="https://min-api.cryptocompare.com/data/price?fsym=USDT&tsyms=USD"]
parse_price_cryptocompare_usdt  [type="jsonparse" path="USD"]

get_price_coinbase_usdt    [type="http" method=GET retries=2 url="https://api.coinbase.com/v2/prices/USDT-USD/spot"]
parse_price_coinbase_usdt  [type="jsonparse" path="data,amount"]

get_price_gateio_usdt     [type="http" method=GET retries=2 url="https://api.gateio.ws/api/v4/spot/tickers?currency_pair=USDT_USD"]
parse_price_gateio_usdt   [type="jsonparse" path="0,last"]

get_price_cryptocompare_usdt -> parse_price_cryptocompare_usdt -> price_mean
get_price_coinbase_usdt -> parse_price_coinbase_usdt -> price_mean
get_price_gateio_usdt -> parse_price_gateio_usdt -> price_mean
price_mean_usdt [type="mean" failEarly=true values=<[$(parse_price_cryptocompare_usdt),$(parse_price_coinbase_usdt),$(parse_price_gateio_usdt)]> precision="$(decode_decimals.decimals)" allowedFaults=2]

get_price_cryptocompare    [type="http" method=GET retries=2 url="https://min-api.cryptocompare.com/data/price?fsym=ETH&tsyms=USD"]
parse_price_cryptocompare  [type="jsonparse" path="USD"]

get_price_huobi        [type="http" method=GET retries=2 url="https://api.huobi.pro/market/detail/merged?symbol=ethusdt"]
parse_price_huobi_tmp  [type="jsonparse" path="tick,close"]
parse_price_huobi      [type="multiply" input="$(parse_price_huobi_tmp)" times="$(price_mean_usdt)"]

get_price_okex    [type="http" method=GET retries=2 url="https://www.okx.com/api/v5/market/ticker?instId=ETH-USD-SWAP"]
parse_price_okex  [type="jsonparse" path="data,0,last"]

get_price_binance        [type="http" method=GET retries=2 url="https://data-api.binance.vision/api/v3/ticker/price?symbol=ETHUSDT"]
parse_price_binance_tmp  [type="jsonparse" path="price"]
parse_price_binance      [type="multiply" input="$(parse_price_binance_tmp)" times="$(price_mean_usdt)"]

get_price_bitfinex    [type="http" method=GET retries=2 url="https://api-pub.bitfinex.com/v2/ticker/tETH:USD"]
parse_price_bitfinex  [type="jsonparse" path="6"]

get_price_coinbase    [type="http" method=GET retries=2 url="https://api.coinbase.com/v2/prices/ETH-USD/spot"]
parse_price_coinbase  [type="jsonparse" path="data,amount"]

get_price_kucoin        [type="http" method=GET retries=2 url="https://api.kucoin.com/api/v1/market/orderbook/level1?symbol=ETH-USDT"]
parse_price_kucoin_tmp  [type="jsonparse" path="data,price"]
parse_price_kucoin      [type="multiply" input="$(parse_price_kucoin_tmp)" times="$(price_mean_usdt)"]

get_price_bybit        [type="http" method=GET retries=2 url="https://api.bybit.com/v5/market/tickers?category=spot&symbol=ETHUSDT"]
parse_price_bybit_tmp  [type="jsonparse" path="result,list,0,lastPrice"]
parse_price_bybit      [type="multiply" input="$(parse_price_bybit_tmp)" times="$(price_mean_usdt)"]

get_price_gateio        [type="http" method=GET retries=2 url="https://api.gateio.ws/api/v4/spot/tickers?currency_pair=ETH_USDT"]
parse_price_gateio_tmp  [type="jsonparse" path="0,last"]
parse_price_gateio      [type="multiply" input="$(parse_price_gateio_tmp)" times="$(price_mean_usdt)"]

get_price_mexc        [type="http" method=GET retries=2 url="https://api.mexc.com/api/v3/ticker/price?symbol=ETHUSDT"]
parse_price_mexc_tmp  [type="jsonparse" path="price"]
parse_price_mexc      [type="multiply" input="$(parse_price_mexc_tmp)" times="$(price_mean_usdt)"]

get_price_hashkey       [type="http" method=GET retries=2 url="https://api-pro.hashkey.com/quote/v1/ticker/price?symbol=ETHUSD"]
parse_price_hashkey     [type="jsonparse" path="0,p"]

get_price_cryptocompare -> parse_price_cryptocompare -> price_mean
get_price_huobi -> parse_price_huobi_tmp -> parse_price_huobi -> price_mean
get_price_okex -> parse_price_okex -> price_mean
get_price_binance -> parse_price_binance_tmp -> parse_price_binance -> price_mean
get_price_bitfinex -> parse_price_bitfinex -> price_mean
get_price_coinbase -> parse_price_coinbase -> price_mean
get_price_kucoin -> parse_price_kucoin_tmp -> parse_price_kucoin -> price_mean
get_price_bybit -> parse_price_bybit_tmp -> parse_price_bybit -> price_mean
get_price_gateio -> parse_price_gateio_tmp -> parse_price_gateio -> price_mean
get_price_mexc -> parse_price_mexc_tmp -> parse_price_mexc -> price_mean
get_price_hashkey -> parse_price_hashkey -> price_mean

price_mean [type="meantrim" failEarly=true values=<[$(parse_price_cryptocompare),$(parse_price_huobi),$(parse_price_okex),$(parse_price_binance),$(parse_price_bitfinex),$(parse_price_coinbase),$(parse_price_kucoin),$(parse_price_bybit),$(parse_price_gateio),$(parse_price_mexc),$(parse_price_hashkey)]> precision="$(decode_decimals.decimals)" allowedFaults=5]

price_multiply [type="multiply" input="$(price_mean)" times="$(decimals_pow)"]
price_mean -> price_multiply
"""